python -m lstm_bert_classification.main \
    --dataloader_workers 2 \
    --seed 42 \
    --epochs 20 \
    --learning_rate 5e-5 \
    --weight_decay 0.01 \
    --warmup_steps 500 \
    --max_length 256 \
    --max_seq_len 6 \
    --pad_mask_id -100 \
    --model vinai/phobert-base-v2 \
    --freeze_bert_layers 0 \
    --model_type lstm \
    --train_batch_size 16 \
    --val_batch_size 16 \
    --test_batch_size 16 \
    --train_file dialogue_dataset/train.json \
    --val_file dialogue_dataset/val.json \
    --test_file dialogue_dataset/test.json \
    --output_dir ./models \
    --record_output_file output.json \
    --early_stopping_patience 5 \
    --early_stopping_threshold 0.001 \
    --focal_loss_gamma 2.0 \
    --focal_loss_alpha 0.25 \
    --use_focal_loss \
    --dynamic_padding \
    --evaluate_on_accuracy \
